# -*- coding: utf-8 -*-
"""nltk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Giz9sVZoAqI2j7WQ-HSVh0erQoJkwuks
"""

!pip install nltk

import nltk
nltk.download('punkt')

sentence = """At eight o'clock on Thursday morning
... Arthur didn't feel very good."""
tokens = nltk.word_tokenize(sentence.lower())
tokens

nltk.download('averaged_perceptron_tagger')
tagged = nltk.pos_tag(tokens) #POS tagger is used to assign grammatical information of each word of the sentence
tagged[0:6]

#named entity recognition (NER), a process that identifies named entities such as persons, organizations, locations, etc., in text data.
nltk.download('maxent_ne_chunker')
#utilized in various natural language processing tasks, such as spell checking, text tokenization, and vocabulary analysis.
nltk.download('words')
#facilitates the visualization of linguistic trees, such as syntax trees or parse trees,
!pip install svgling
named_entities = nltk.ne_chunk(tagged)
named_entities

